services:
  php:
    build: ./docker/php
    container_name: symfony_php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - postgres

  node:
    image: node:20-alpine
    container_name: symfony_frontend
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Чтобы Vite корректно видел изменения файлов через Docker

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/backend/public
    depends_on:
      - php
#      - node

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
